Feature/issue 10
nromanen/Ch-133.Ruby pull request #16
Opened 2022-02-17 08:58 UTC by Faustiks

# Description

add user_info controller and model with validations 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-17 14:25 UTC, kapatsila-mariia approved these changes

2022-02-18 12:43 UTC, bearded requested changes

2022-02-18 12:43 UTC, bearded commented on server/app/controllers/user_infos_controller.rb
> +    render json: show_user_info.to_json(:only => [ :id, :first_name,
would be good to use json serializer, or separate method that would return json
to follow principle DRY (Don't repeat yourself)

2022-02-18 12:43 UTC, bearded commented on server/app/controllers/user_infos_controller.rb
> +  def create_user_info_params
seems like one method `user_info_params` would be enough, to not duplicate the same code...

2022-02-18 12:43 UTC, bearded commented on server/config/routes.rb
> +  put 'user_infos', to: 'user_infos#update'
would be good to use singular form of "resource" for UserInfo
e.g.
```ruby
resources :users do
  resource :user_info
end
```
ref: https://guides.rubyonrails.org/routing.html#singular-resources

2022-02-21 08:55 UTC, bearded approved these changes
Looks good

2022-02-21 14:02 UTC, merged