create basic project
nromanen/Ch-133.Ruby pull request #7
Opened 2022-02-09 14:48 UTC by Faustiks

# Description

created basic project
add gems: 
gem 'pg', '1.3.0.rc3'
gem 'rspec', '\~> 3.5'
gem 'fast_jsonapi'
gem 'rubocop', require: false
gem 'oj', '~> 3.3', '>= 3.3.5'
gem 'devise'
gem 'devise-jwt'
gem 'uuid'
gem 'rack-cors'

add models
add device\device-jwt registration\authentication

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-14 12:16 UTC, bearded requested changes

2022-02-14 12:16 UTC, bearded commented on server/Gemfile
> +gem "rubocop-rails_config"
Those gems have to be specified in the section `group :development, :test do` 
see line 49 in this file

2022-02-14 12:16 UTC, bearded commented on server/README.md
> +* Ruby version
would be good to mention which ruby/rails/db versions will be used in this project
and which command have to be executed to run the project

2022-02-14 12:16 UTC, bearded commented on server/Gemfile
> +gem "rubocop-rails_config"
please also add gems `rspec-rails` and `simplecov`

2022-02-14 12:16 UTC, bearded commented on server/config/database.yml
> +  password: DgefKlipsa
please use empty password, as it may cause problems for other people to connect DB

2022-02-16 15:05 UTC, Faustiks commented on server/README.md
> +* Ruby version
will be added later in next PR

2022-02-16 15:17 UTC, kapatsila-mariia approved these changes

2022-02-16 15:18 UTC, le-murier approved these changes

2022-02-16 15:19 UTC, merged