Feature/issue 80
nromanen/Ch-133.Ruby pull request #73
Opened 2022-04-17 23:42 UTC by le-murier

# Description

Was added likes controller and modified react component

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-17 23:43 UTC, le-murier commented
![зображення](https://user-images.githubusercontent.com/82406343/163736450-578cbbd0-b557-4365-887d-00253b623afd.png)
![зображення](https://user-images.githubusercontent.com/82406343/163736455-b6ba40aa-2c80-4722-9020-c7224c4e9095.png)
![зображення](https://user-images.githubusercontent.com/82406343/163736458-c8728726-9933-4fa8-b0a4-6c2e5bf231e3.png)

2022-04-17 23:47 UTC, le-murier commented
now routes is 
```
  get 'adverts/:id/liked', to: 'likes#index'
  get 'adverts/:id/likes', to: 'likes#amount'
  post 'adverts/:id/likes', to: 'likes#create'
  delete 'adverts/:id/likes', to: 'likes#destroy'
```
with :resourse
![зображення](https://user-images.githubusercontent.com/82406343/163736518-d2168bce-31a1-48b3-9c93-6eb6d40b32f0.png)
but user can create only one like, so i don't think that /likes/:it will have sense

2022-04-21 12:51 UTC, bearded requested changes

2022-04-21 12:51 UTC, bearded commented on server/config/routes.rb
>  end
would be good to use nested resources here, similar to comments...
actually those 3 routes had to be added at line 23, e.g.:

```ruby
resources :adverts do
    resources :comments
    resources :likes, only: [:index, :create, :destroy]
end
```

and action `liked` should be moved into likes controller and be named index according to REST :)

2022-04-21 18:22 UTC, le-murier commented on server/app/controllers/likes_controller.rb
> +    like = advert.likes.where(user_id: current_user.try(:id)).first
It doesn't look like much, but I don't know how to do it better

2022-04-25 19:47 UTC, bearded commented on server/app/controllers/likes_controller.rb
> +      like.save
method save does trigger method `valid?`, so that it could be just `if like.save`

2022-04-25 19:48 UTC, bearded commented on server/app/controllers/likes_controller.rb
> +      like.destroy()
could be `like&.destroy` or `like.try(:destroy)`

2022-04-25 19:50 UTC, bearded approved these changes

2022-04-26 11:44 UTC, merged