Feature/issue 67
nromanen/Ch-133.Ruby pull request #74
Opened 2022-04-19 14:29 UTC by kapatsila-mariia

# Description

Created page for showing advert with components for each part of advertisement;
Added serializer for comment;
Updated serializer for advert;

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-19 14:32 UTC, kapatsila-mariia commented
![adv1](https://user-images.githubusercontent.com/55360944/164028302-44418f34-85d3-425b-b7f0-bf19b501358e.png)
![adv2](https://user-images.githubusercontent.com/55360944/164028313-b8b356a2-90af-4ac6-8811-a971cfb6b9a7.png)

2022-04-21 12:58 UTC, bearded requested changes

2022-04-21 12:58 UTC, bearded commented on server/app/controllers/comments_controller.rb
> +      render json: @comment, serializer: CommentSerializer
it seems like it should be still @comments, as `set_comment` is not executed for `index` , so that variable @comment is not defined

2022-04-21 18:50 UTC, le-murier submitted a review, later dismissed

2022-04-22 13:34 UTC, bearded approved these changes

2022-04-22 13:52 UTC, bearded approved these changes

2022-04-22 13:57 UTC, merged